# Generated by Django 3.2.15 on 2022-09-23 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_scrapyd', '0004_auto_20220905_1014'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyErrLogRate',
        ),
        migrations.DeleteModel(
            name='ErrorLog',
        ),
        migrations.DeleteModel(
            name='HourlyErrLogRate',
        ),
    ]
