# Generated by Django 3.2.12 on 2022-06-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogServer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('addr', models.CharField(max_length=50, unique=True)),
                ('alias', models.CharField(default='', max_length=100)),
                ('is_default', models.SmallIntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now=True, db_index=True)),
                ('update_time', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapydServer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('addr', models.CharField(max_length=50, unique=True)),
                ('alias', models.CharField(default='', max_length=100)),
                ('is_default', models.SmallIntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now=True, db_index=True)),
                ('update_time', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
