# Generated by Django 3.2.12 on 2022-09-20 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogServer',
        ),
    ]
