# Generated by Django 3.2.15 on 2022-11-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0002_delete_logserver'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailSender',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mail_addr', models.CharField(max_length=255)),
                ('mail_port', models.IntegerField(default=465)),
                ('server_addr', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(auto_now=True, db_index=True)),
                ('update_time', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
