# Generated by Django 3.2.15 on 2022-11-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0003_mailsender'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailsender',
            name='auth_code',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
