# Generated by Django 3.2.12 on 2022-09-05 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_scrapyd', '0003_auto_20220812_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spiderstats',
            name='last_run',
        ),
        migrations.RemoveField(
            model_name='spiderstats',
            name='run_type',
        ),
        migrations.RemoveField(
            model_name='spiderstats',
            name='trigger',
        ),
    ]
