# Generated by Django 3.2.15 on 2023-07-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorrules',
            name='start_params',
            field=models.CharField(max_length=1000, null=True, verbose_name='启动参数'),
        ),
    ]
