# Generated by Django 3.2.15 on 2023-07-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_schedule', '0002_monitorrules_start_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorrules',
            name='description',
            field=models.CharField(max_length=2000, null=True, verbose_name='说明'),
        ),
    ]
